spring:
  datasource:
    url: jdbc:mysql://39.108.216.235:3306/security?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888

my:
  security:
